@startuml

title Gogeta Architecture

[Gogeta API] as api
[Cache] as cache
[Gogeta Queue] as gogeta_queue
[Gogeta Processor] as processor
[AI Queue] as ai_queue
[AI Service] as ai_service
[Hosting Service] as hosting_service

api - gogeta_queue
api --> cache

gogeta_queue - processor
processor --> cache
processor - ai_queue 

ai_queue - ai_service
ai_service --> hosting_service

@enduml
