@startuml netflix clone

database "Original content" as original_cont
database "Transcoding content" as transcoding_cont
component "Transcoding service" as transcoding_serv
component "Playback service" as playback_serv
queue "Playback queue" as playback_queue
storage "Playback repository" as playback_repo
card "Play API" as play_api

database "User data" as user_data
component "Authenticate service" as auth_serv
card "Sign-in/Sign-up API" as sign_api
component "Personalize service" as personalize_serv
card "Personalize API" as personalize_api

component "Discovery service" as discovery_serv
queue "Discovery queue" as discovery_queue
storage "Discovery repository" as discovery_repo
card "Discovery API" as discovery_api

component "Load balancer" as load_balancer
component "User device" as user_device

original_cont -- transcoding_serv
transcoding_serv -- transcoding_cont
transcoding_cont -- playback_serv
playback_serv -- playback_queue
playback_serv -- playback_repo
playback_queue -- play_api
playback_repo -- play_api

user_data -- auth_serv
auth_serv -- sign_api
user_data -- personalize_serv
personalize_serv -- personalize_api

transcoding_cont -- discovery_serv
user_data -- discovery_serv
discovery_serv -- discovery_queue
discovery_serv -- discovery_repo
discovery_queue -- discovery_api
discovery_repo -- discovery_api

sign_api -- load_balancer
personalize_api -- load_balancer
play_api -- load_balancer
discovery_api -- load_balancer

load_balancer -- user_device

@enduml