participant Client
participant Gogeta_Api
participant Queue
participant Cache

@startuml
Client -> Gogeta_Api: send requestAi
Gogeta_Api --> Gogeta_Api: transfer info from Request to AITrans
Gogeta_Api --> Gogeta_Api: validate AITrans
Gogeta_Api --> Cache: save AITrans to cache
Gogeta_Api --> Queue: send AiTrans to queue to process this AITrans
Gogeta_Api --> Client: return response to client
@enduml
